version: 1
handlers:
  console:
    class: logging.StreamHandler
    formatter: normal
    filters: [userid]
filters:
  userid:
    (): dexter.logs.userIdFilterFactory
    class: dexter.logs.UserIdFilter
formatters:
  normal:
    format: '%(asctime)s %(process)-6d %(name)-12s %(userid)s %(levelname)-8s %(message)s'
loggers:
  requests:
    level: INFO
  sqlalchemy.engine:
    level: INFO
  dexter.models.person:
    level: DEBUG
  dexter.models.document:
    level: DEBUG
root:
  handlers: [console]
  level: INFO
